//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rsteam.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feivarit
    {
        public int id_feit { get; set; }
        public int User_id { get; set; }
        public int Game_id { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Games Games { get; set; }
    }
}
