//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rsteam.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibrarysGames
    {
        public int id_LibGame { get; set; }
        public int Game_id { get; set; }
        public int Library_id { get; set; }
        public Nullable<System.DateTime> LastStartDate { get; set; }
    
        public virtual Librarys Librarys { get; set; }
        public virtual Games Games { get; set; }
    }
}
