//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClMan.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chats
    {
        public int id_chats { get; set; }
        public string Text { get; set; }
        public int FS_id { get; set; }
        public int User_id { get; set; }
        public System.DateTime DateTime { get; set; }
        public byte[] Photo { get; set; }
        public string Files { get; set; }
        public string Link { get; set; }
    
        public virtual FrendSection FrendSection { get; set; }
        public virtual Users Users { get; set; }
    }
}
