//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClMan.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creaters
    {
        public int Id_creater { get; set; }
        public int Prodaction_id { get; set; }
        public string Name { get; set; }
        public int User_id { get; set; }
    
        public virtual Prodactions Prodactions { get; set; }
        public virtual Users Users { get; set; }
    }
}
