//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vizard.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerAppeal
    {
        public int id_Answer { get; set; }
        public string Text { get; set; }
        public int User_id { get; set; }
        public int Appeal_id { get; set; }
        public System.DateTime DateAnswer { get; set; }
    
        public virtual Appeal Appeal { get; set; }
        public virtual Users Users { get; set; }
    }
}
