//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vizard.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Games()
        {
            this.Feivarit = new HashSet<Feivarit>();
            this.GameComments = new HashSet<GameComments>();
            this.LibrarysGames = new HashSet<LibrarysGames>();
        }
    
        public int id_game { get; set; }
        public string Title { get; set; }
        public byte[] Photo { get; set; }
        public int prodaction_id { get; set; }
        public System.DateTime DataCreate { get; set; }
        public decimal Price { get; set; }
        public int Reiting_id { get; set; }
        public Nullable<int> IsBlocet { get; set; }
        public string PathFoGame { get; set; }
    
        public virtual Blocet Blocet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feivarit> Feivarit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameComments> GameComments { get; set; }
        public virtual Prodactions Prodactions { get; set; }
        public virtual Reiteg Reiteg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibrarysGames> LibrarysGames { get; set; }
    }
}
