//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vizard.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameComments
    {
        public int id_GameComment { get; set; }
        public string Text { get; set; }
        public int User_id { get; set; }
        public int Game_id { get; set; }
        public int IsBlocet { get; set; }
    
        public virtual Blocet Blocet { get; set; }
        public virtual Games Games { get; set; }
        public virtual Users Users { get; set; }
    }
}
